# Generated by Django 2.2.4 on 2019-08-16 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyroad', '0002_auto_20190815_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='total_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
