# Generated by Django 2.2.4 on 2019-08-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyroad', '0003_auto_20190816_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
